@startuml
skinparam NodeBackgroundColor DeepSkyBlue 

title MaryApp Architecture

/' Nodes '/
node  AppModule #LightSeaGreen
node CoreModule #IndianRed
note bottom : Components, Button, Pipe, Directives...
node SharedModule #MediumPurple
note bottom : Service, Intercepteurs, Guards
node GEDModule #LightGoldenRodYellow {
    node SearchModule
    node DepositModule
    node SharedGEDModule {
        [DatePipe]
    }
}

/' Relations '/
AppModule --> CoreModule
AppModule --> SharedModule
AppModule --> GEDModule


@enduml