@startuml Class_Diagramm
skinparam roundcorner 20
skinparam class {
BackgroundColor AliceBlue
ArrowColor DodgerBlue
BorderColor AntiqueWhite
}
skinparam stereotypeCBackgroundColor Chartreuse
skinparam stereotypeABackgroundColor DeepSkyBlue
skinparam stereotypeEBackgroundColor DarkOrchid

title Modèle de données
legend Ce modèle permet de décrire la relation entre les données utilisées dans notre application

class User {
    firstname : String
    lastname : String
    email : String
    
}

enum ERole{
    ADMIN
    EMPLOYEE
}

abstract "Document" as Document{
    id : Int
    date : Date
    deposit_author : User
    deposit_date : Date 
    description : String? 
}

abstract BilingDoc {
    ttcAmount : Float 
    htAmount : Float 
}

class InvoiceDoc 

enum InvoiceDocType {
    CLIENT
    SUPPLIER
}

class OrderDoc 

enum OrderDocType {
    DELIVERY
    PURCHASE
}

class EmployeeDoc

enum EmployeeDocType {
    PAYSLIP
    ID_CARD
    VITAL_CARD
    OTHER
}

class AdministrativeDoc {
    title : String
}

enum EDocumentType{
    INVOICE
    ORDER
    ADMINISTRATIVE
    EMPLOYEE
    OTHER
}

User "*" -- "1" ERole
Document -> User

Document -> EDocumentType
Document <|-- BilingDoc
Document <|-- EmployeeDoc
Document <|-- AdministrativeDoc

BilingDoc <|-- InvoiceDoc
BilingDoc <|-- OrderDoc

InvoiceDoc -> InvoiceDocType
OrderDoc -> OrderDocType
EmployeeDocType <- EmployeeDoc

@enduml